* Add man doc generation for kdb & elektra
git-svn-id: https://svn.libelektra.org/svn/elektra/trunk@309 3c96aef2-7adb-0310-a8e7-cbd0541efc33

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,9 +7,6 @@
 # Copyright (C) 2003 Free Software Foundation, Inc.
 # This configure script is free software; the Free Software Foundation
 # gives unlimited permission to copy, distribute and modify it.
-#
-# $Id$
-#
 ## --------------------- ##
 ## M4sh Initialization.  ##
 ## --------------------- ##
@@ -469,7 +466,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar default_backend LTDLINCL LIBLTDL CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PKG_CONFIG ac_pt_PKG_CONFIG subdirs XML2_CONFIG XML_CPPFLAGS XML_LIBS HAVE_XML_TRUE HAVE_XML_FALSE HAVE_DB_TRUE HAVE_DB_FALSE gconf_CFLAGS gconf_LIBS HAVE_GCONF_TRUE HAVE_GCONF_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar default_backend LTDLINCL LIBLTDL CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL PKG_CONFIG ac_pt_PKG_CONFIG subdirs xsltproc dbroot HAVE_XSLTPROC_TRUE HAVE_XSLTPROC_FALSE man2html HAVE_MAN2HTML_TRUE HAVE_MAN2HTML_FALSE doxygen HAVE_DOXYGEN_TRUE HAVE_DOXYGEN_FALSE XML2_CONFIG XML_CPPFLAGS XML_LIBS HAVE_XML_TRUE HAVE_XML_FALSE HAVE_DB_TRUE HAVE_DB_FALSE gconf_CFLAGS gconf_LIBS HAVE_GCONF_TRUE HAVE_GCONF_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19843,23 +19840,189 @@ subdirs="$subdirs libltdl"
 # Check needed programs for generate doc
 
 # xsltproc
-#AC_PATH_PROG(xsltproc, xsltproc, "no")
-#if test $xsltproc!="no"; then
-#	# xslproc was found, check for stylesheet
-#	AC_CHECK_FILE([/usr/share/sgml/docbook/xsl-stylesheets/manpages/docbook.xsl],
-#		      [[dbroot="/usr/share/sgml/docbook/xsl-stylesheets/"]],
-#		      AC_MSG_ERROR([Can't find DocBook stylesheets]))
-#	AC_SUBST(dbroot)
-# fi
-# AM_CONDITIONAL(HAVE_XSLTPROC, test $xsltproc!="no")
+# Extract the first word of "xsltproc", so it can be a program name with args.
+set dummy xsltproc; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_xsltproc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $xsltproc in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_xsltproc="$xsltproc" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_xsltproc="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_xsltproc" && ac_cv_path_xsltproc=""no""
+  ;;
+esac
+fi
+xsltproc=$ac_cv_path_xsltproc
+
+if test -n "$xsltproc"; then
+  echo "$as_me:$LINENO: result: $xsltproc" >&5
+echo "${ECHO_T}$xsltproc" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test $xsltproc!="no"; then
+	# xslproc was found, check for stylesheet
+	echo "$as_me:$LINENO: checking for /usr/share/sgml/docbook/xsl-stylesheets/manpages/docbook.xsl" >&5
+echo $ECHO_N "checking for /usr/share/sgml/docbook/xsl-stylesheets/manpages/docbook.xsl... $ECHO_C" >&6
+if test "${ac_cv_file__usr_share_sgml_docbook_xsl_stylesheets_manpages_docbook_xsl+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/usr/share/sgml/docbook/xsl-stylesheets/manpages/docbook.xsl"; then
+  ac_cv_file__usr_share_sgml_docbook_xsl_stylesheets_manpages_docbook_xsl=yes
+else
+  ac_cv_file__usr_share_sgml_docbook_xsl_stylesheets_manpages_docbook_xsl=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__usr_share_sgml_docbook_xsl_stylesheets_manpages_docbook_xsl" >&5
+echo "${ECHO_T}$ac_cv_file__usr_share_sgml_docbook_xsl_stylesheets_manpages_docbook_xsl" >&6
+if test $ac_cv_file__usr_share_sgml_docbook_xsl_stylesheets_manpages_docbook_xsl = yes; then
+  dbroot="/usr/share/sgml/docbook/xsl-stylesheets/"
+else
+  { { echo "$as_me:$LINENO: error: Can't find DocBook stylesheets" >&5
+echo "$as_me: error: Can't find DocBook stylesheets" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+fi
+
+
+if test $xsltproc!="no"; then
+  HAVE_XSLTPROC_TRUE=
+  HAVE_XSLTPROC_FALSE='#'
+else
+  HAVE_XSLTPROC_TRUE='#'
+  HAVE_XSLTPROC_FALSE=
+fi
+
 
 # man2html
-# AC_PATH_PROG(man2html, man2html, "no")
-# AM_CONDITIONAL(HAVE_MAN2HTML, test $man2html!="no")
+# Extract the first word of "man2html", so it can be a program name with args.
+set dummy man2html; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_man2html+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $man2html in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_man2html="$man2html" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_man2html="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_man2html" && ac_cv_path_man2html=""no""
+  ;;
+esac
+fi
+man2html=$ac_cv_path_man2html
+
+if test -n "$man2html"; then
+  echo "$as_me:$LINENO: result: $man2html" >&5
+echo "${ECHO_T}$man2html" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test $man2html!="no"; then
+  HAVE_MAN2HTML_TRUE=
+  HAVE_MAN2HTML_FALSE='#'
+else
+  HAVE_MAN2HTML_TRUE='#'
+  HAVE_MAN2HTML_FALSE=
+fi
+
 
 # Doxygen
-# AC_PATH_PROG(doxygen, doxygen, "no")
-# AM_CONDITIONAL(HAVE_DOXYGEN, test $doxygen!="no")
+# Extract the first word of "doxygen", so it can be a program name with args.
+set dummy doxygen; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_doxygen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $doxygen in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_doxygen="$doxygen" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_doxygen="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_doxygen" && ac_cv_path_doxygen=""no""
+  ;;
+esac
+fi
+doxygen=$ac_cv_path_doxygen
+
+if test -n "$doxygen"; then
+  echo "$as_me:$LINENO: result: $doxygen" >&5
+echo "${ECHO_T}$doxygen" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test $doxygen!="no"; then
+  HAVE_DOXYGEN_TRUE=
+  HAVE_DOXYGEN_FALSE='#'
+else
+  HAVE_DOXYGEN_TRUE='#'
+  HAVE_DOXYGEN_FALSE=
+fi
+
 
 #
 # Checks for libraries.
@@ -21591,7 +21754,7 @@ done
 #
           ac_config_files="$ac_config_files Makefile"
 
-                                                                                                                                                      ac_config_files="$ac_config_files src/Makefile src/libelektra/Makefile src/libelektratools/Makefile src/libregistry/Makefile src/kdb/Makefile src/backends/Makefile src/backends/berkeleydb/Makefile src/backends/filesys/Makefile src/backends/fstab/Makefile src/backends/ini/Makefile src/backends/gconf/Makefile src/backends/template/Makefile src/include/Makefile example/Makefile elektra.pc"
+                                                                                                                                                                ac_config_files="$ac_config_files src/Makefile src/libelektra/Makefile src/libelektratools/Makefile src/libregistry/Makefile src/kdb/Makefile src/backends/Makefile src/backends/berkeleydb/Makefile src/backends/filesys/Makefile src/backends/fstab/Makefile src/backends/ini/Makefile src/backends/gconf/Makefile src/backends/template/Makefile src/include/Makefile example/Makefile doc/Makefile elektra.pc"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -21701,6 +21864,27 @@ if test -z "${am__fastdepCXX_TRUE}" && test -z "${am__fastdepCXX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_XSLTPROC_TRUE}" && test -z "${HAVE_XSLTPROC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_XSLTPROC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_XSLTPROC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_MAN2HTML_TRUE}" && test -z "${HAVE_MAN2HTML_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MAN2HTML\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_MAN2HTML\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_DOXYGEN_TRUE}" && test -z "${HAVE_DOXYGEN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_DOXYGEN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_DOXYGEN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22184,6 +22368,7 @@ do
   "src/backends/template/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/backends/template/Makefile" ;;
   "src/include/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/include/Makefile" ;;
   "example/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/Makefile" ;;
+  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "elektra.pc" ) CONFIG_FILES="$CONFIG_FILES elektra.pc" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
@@ -22343,6 +22528,16 @@ s,@LIBTOOL@,$LIBTOOL,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
 s,@ac_pt_PKG_CONFIG@,$ac_pt_PKG_CONFIG,;t t
 s,@subdirs@,$subdirs,;t t
+s,@xsltproc@,$xsltproc,;t t
+s,@dbroot@,$dbroot,;t t
+s,@HAVE_XSLTPROC_TRUE@,$HAVE_XSLTPROC_TRUE,;t t
+s,@HAVE_XSLTPROC_FALSE@,$HAVE_XSLTPROC_FALSE,;t t
+s,@man2html@,$man2html,;t t
+s,@HAVE_MAN2HTML_TRUE@,$HAVE_MAN2HTML_TRUE,;t t
+s,@HAVE_MAN2HTML_FALSE@,$HAVE_MAN2HTML_FALSE,;t t
+s,@doxygen@,$doxygen,;t t
+s,@HAVE_DOXYGEN_TRUE@,$HAVE_DOXYGEN_TRUE,;t t
+s,@HAVE_DOXYGEN_FALSE@,$HAVE_DOXYGEN_FALSE,;t t
 s,@XML2_CONFIG@,$XML2_CONFIG,;t t
 s,@XML_CPPFLAGS@,$XML_CPPFLAGS,;t t
 s,@XML_LIBS@,$XML_LIBS,;t t
