YAML Benchmark: Move input files to other repo

diff --git a/scripts/benchmark-yaml.in b/scripts/benchmark-yaml.in
--- a/scripts/benchmark-yaml.in
+++ b/scripts/benchmark-yaml.in
@@ -8,13 +8,14 @@
 BUILD_DIRECTORY="@CMAKE_BINARY_DIR@"
 SOURCE_DIRECTORY="@CMAKE_SOURCE_DIR@"
 PLUGINS=(yamlcpp yanlr yambi yawn yaypeg)
-DATA_DIRECTORY="benchmarks/data/temporary"
+DATA_DIRECTORY="benchmarks/data"
 BENCHMARK_TOOL="$BUILD_DIRECTORY/bin/benchmark_plugingetset"
 INPUT_FILES=(
-	benchmarks/data/keyframes.yaml
-	benchmarks/data/combined.yaml
-	benchmarks/data/generated.yaml
+	keyframes.yaml
+	combined.yaml
+	generated.yaml
 )
+INPUT_URL="https://raw.githubusercontent.com/sanssecours/rawdata/master/YAML"
 
 trap cleanup EXIT INT QUIT TERM
 
@@ -34,8 +35,28 @@ write() {
 	kdb umount "$KDBPATH"
 }
 
+download() {
+	mkdir -p "$DATA_DIRECTORY" || {
+		printf >&2 'Unable to create download directory “%s”\n' "$DATA_DIRECTORY"
+		exit 1
+	}
+	for INPUT_FILE in "${INPUT_FILES[@]}"; do
+		OUTPUT=$(curl 2>&1 -L "$INPUT_URL/$INPUT_FILE" -o "$DATA_DIRECTORY/$INPUT_FILE")
+		if [ $? != 0 ]; then
+			printf >&2 'Unable to download “%s” as “%s”\n:' "$INPUT_URL/$INPUT_FILE" "$DATA_DIRECTORY/$INPUT_FILE"
+			printf >&2 '%s\n' "$OUTPUT"
+			exit 1
+		fi
+	done
+}
+
 cd "$SOURCE_DIRECTORY" || {
 	printf >&2 'Unable to change working directory to “%s”\n' "$SOURCE_DIRECTORY"
+	exit 1
+}
+
+command -v curl > /dev/null 2>&1 || {
+	printf >&2 'This script requires the command `curl`\n'
 	exit 1
 }
 
@@ -44,8 +65,11 @@ command -v hyperfine > /dev/null 2>&1 || {
 	exit 1
 }
 
-for INPUT_FILE in "${INPUT_FILES[@]}"; do
+download
+
+for FILEPATH in "${INPUT_FILES[@]}"; do
 	REFERENCE=reference.yaml
+	INPUT_FILE="$DATA_DIRECTORY/$FILEPATH"
 	write yamlcpp "$INPUT_FILE" "$REFERENCE"
 	for PLUGIN in "${PLUGINS[@]}"; do
 		write "$PLUGIN" "$INPUT_FILE" "$PLUGIN.yaml"
@@ -59,12 +83,11 @@ for INPUT_FILE in "${INPUT_FILES[@]}"; do
 	rm "$REFERENCE"
 done
 
-mkdir "$DATA_DIRECTORY"
 for FILEPATH in "${INPUT_FILES[@]}"; do
-	DIRECTORY="$DATA_DIRECTORY/$(basename "$FILEPATH" | cut -f1 -d'.')"
+	DIRECTORY="$DATA_DIRECTORY/$(printf '%s' "$FILEPATH" | cut -f1 -d'.')"
 	mkdir "$DIRECTORY"
 	for PLUGIN in "${PLUGINS[@]}"; do
-		cp "$FILEPATH" "$DIRECTORY/test.$PLUGIN.in"
+		cp "$DATA_DIRECTORY/$FILEPATH" "$DIRECTORY/test.$PLUGIN.in"
 	done
 done
 
