doc: error message if no source dir given
allow to pass further CMake commands

fixes #2525

diff --git a/scripts/configure-common b/scripts/configure-common
--- a/scripts/configure-common
+++ b/scripts/configure-common
@@ -7,8 +7,15 @@ SCRIPTS_DIR=$(dirname "$0")
 SBUILD=$(pwd)
 BUILD=$(readlink -f "$SBUILD")
 
-if [ -d "$1" ]; then
-	SOURCE=$(readlink -f "$1")
+for last; do true; done
+
+if [ -d "$last" ]; then
+	SOURCE=$(readlink -f "$last")
+else
+	echo "Usage: $SELF [Further CMake Arguments] Elektra-source-dir"
+	echo
+	echo "Error: You did not provide the source directory to Elektra as argument"
+	exit 1
 fi
 
 if [ "$SOURCE" = "$BUILD" ]; then
