allow in source builds, see #436

diff --git a/scripts/configure-common b/scripts/configure-common
--- a/scripts/configure-common
+++ b/scripts/configure-common
@@ -13,8 +13,17 @@ fi
 
 if [ "$SOURCE" = "$BUILD" ]
 then
-	echo "In source builds are not allowed, create a new directory and run $SELF there"
-	exit 1
+	if echo $* | grep FORCE_IN_SOURCE_BUILD=ON
+	then
+		echo "Warning: in source build!"
+		echo "It is recommended to create a new directory and run $SELF there"
+		echo "Proceeding as requested"
+	else
+		echo "Error: in source build!"
+		echo "It is recommended to create a new directory and run $SELF there"
+		echo "You can force an in-tree build with -DFORCE_IN_SOURCE_BUILD=ON"
+		exit 1
+	fi
 fi
 
 if [ "$SCRIPTS" = "$BUILD" ]
