build: put automatic rerun-failed behind env-var

diff --git a/scripts/dev/run_checkshell.in b/scripts/dev/run_checkshell.in
--- a/scripts/dev/run_checkshell.in
+++ b/scripts/dev/run_checkshell.in
@@ -10,6 +10,14 @@ if [ $# -ne 1 ]; then
 	exit 1
 fi
 
-ARGS="-j@PROCESSOR_COUNT@ --force-new-ctest-process --rerun-failed --output-on-failure -R testscr_check --build-config $1"
+ARGS="-j@PROCESSOR_COUNT@ --force-new-ctest-process --output-on-failure -R testscr_check --build-config $1"
 # shellcheck disable=SC2086
-ctest $ARGS || ctest $ARGS --rerun-failed
+if ! ctest $ARGS && [ "$ELEKTRA_AUTO_RERUN" = "1" ]; then
+	echo ""
+	echo "----------------------------------------"
+	echo "| Automatically rerunning failed tests |"
+	echo "----------------------------------------"
+	echo ""
+
+	ctest $ARGS --rerun-failed
+fi
diff --git a/scripts/dev/run_memcheck.in b/scripts/dev/run_memcheck.in
--- a/scripts/dev/run_memcheck.in
+++ b/scripts/dev/run_memcheck.in
@@ -7,4 +7,12 @@ fi
 
 ARGS="-j@PROCESSOR_COUNT@ --force-new-ctest-process -T memcheck --build-config $1 --output-on-failure -LE memleak"
 # shellcheck disable=SC2086
-ctest $ARGS || ctest $ARGS --rerun-failed
+if ! ctest $ARGS && [ "$ELEKTRA_AUTO_RERUN" = "1" ]; then
+	echo ""
+	echo "----------------------------------------"
+	echo "| Automatically rerunning failed tests |"
+	echo "----------------------------------------"
+	echo ""
+
+	ctest $ARGS --rerun-failed
+fi
diff --git a/scripts/dev/run_nokdbtests.in b/scripts/dev/run_nokdbtests.in
--- a/scripts/dev/run_nokdbtests.in
+++ b/scripts/dev/run_nokdbtests.in
@@ -9,4 +9,12 @@ fi
 
 ARGS="-j@PROCESSOR_COUNT@ -LE kdbtests --force-new-ctest-process --output-on-failure --build-config $1"
 # shellcheck disable=SC2086
-ctest $ARGS || ctest $ARGS --rerun-failed
+if ! ctest $ARGS && [ "$ELEKTRA_AUTO_RERUN" = "1" ]; then
+	echo ""
+	echo "----------------------------------------"
+	echo "| Automatically rerunning failed tests |"
+	echo "----------------------------------------"
+	echo ""
+
+	ctest $ARGS --rerun-failed
+fi
