actions: add macOS build matrix

diff --git a/.github/workflows/macOS.yml b/.github/workflows/macOS.yml
--- a/.github/workflows/macOS.yml
+++ b/.github/workflows/macOS.yml
@@ -1,4 +1,4 @@
-name: macOS
+name: 🍎 macOS
 
 # Triggers the workflow on push or pull request events
 on: [push, pull_request]
@@ -19,13 +19,30 @@ jobs:
     strategy:
       matrix:
        include:
-         - name: GCC 10
-           CC: gcc-10
-           CXX: g++-10
-           # Unfortunately the tests for the Xerces plugin fail: https://travis-ci.org/ElektraInitiative/libelektra/jobs/483331657#L3740
-           # The curlget tests fail: https://github.com/ElektraInitiative/libelektra/issues/3382
-           PLUGINS: 'ALL;-xerces;-curlget'
-           BINDINGS: 'ALL;-rust'
+         - name: 🍎 GCC 11
+           env:
+             CC: gcc-11
+             CXX: g++-11
+             # Unfortunately the tests for the Xerces plugin fail: https://travis-ci.org/ElektraInitiative/libelektra/jobs/483331657#L3740
+             # The curlget tests fail: https://github.com/ElektraInitiative/libelektra/issues/3382
+             PLUGINS: 'ALL;-xerces;-curlget'
+             BINDINGS: 'ALL;-rust'
+         - name: 🍎 Clang
+           env:
+             ENABLE_LOGGER: ON
+             TOOLS: ALL;web
+             # The curlget tests fail: https://github.com/ElektraInitiative/libelektra/issues/3382
+             # The augeas tests fail: https://github.com/ElektraInitiative/libelektra/issues/3743
+             PLUGINS: ALL;-curlget;-augeas
+         - name: 🍎 Clang ASAN
+           env:
+             ASAN_OPTIONS: 'detect_leaks=1'
+             ENABLE_ASAN: ON
+             TOOLS: kdb
+             # The curlget tests fail: https://github.com/ElektraInitiative/libelektra/issues/3382
+             # The augeas tests fail: https://github.com/ElektraInitiative/libelektra/issues/3743
+             PLUGINS: ALL;-curlget;-augeas
+             BINDINGS: cpp
 
     steps:
     - uses: actions/checkout@v2
@@ -39,30 +56,59 @@ jobs:
 
     - name: Install Dependencies
       run: |
+        echo $CC
+        echo $CXX
         brew update
         brew config
         brew install augeas \
+          antlr \
+          antlr4-cpp-runtime \
           bison \
+          clang-format \
           dbus \
           discount \
+          doxygen \
           flex \
+          glib \
+          go \
           gpgme \
+          gradle \
+          graphviz \
           libev \
           libgcrypt \
           libgit2 \
           libuv \
+          llvm \
           lua \
+          moreutils \
           ninja \
+          npm \
+          oclint/formulae/oclint \
+          openssl \
+          pkg-config \
           qt \
+          shfmt \
           swig \
+          tree \
+          xerces-c \
           yajl \
+          yaml-cpp \
           zeromq
         brew install --cask adoptopenjdk
+        # Try to install `checkbashisms` (The file server that hosts the package is unfortunately quite unreliable.)
+        brew install checkbashisms || >&2 printf 'Warning: Unable to install `checkbashims`\n'
 
     - name: Setup Build Environment
       run: |
+        # Install Ruby gems
+        gem install ronn-ng -v 0.10.1.pre1
         gem install test-unit --no-document
+        # Install Python packages
         pip2 install cheetah # Required by kdb-gen
+        pip3 install cmakelang[yaml]==0.6.13
+        # Install JavaScript packages
+        npm install dredd --global
+        npm install --global prettier@2.2.1
         brew tap homebrew/services
         brew update # Work around for [Homebrew Services issue 206](https://github.com/Homebrew/homebrew-services/issues/206)
         brew postinstall dbus
@@ -91,6 +137,7 @@ jobs:
           -DBUILD_SHARED="${BUILD_SHARED:-ON}"
           -DENABLE_ASAN="${ENABLE_ASAN:-OFF}"
           -DCOMMON_FLAGS="${COMMON_FLAGS--Werror}"
+          -DENABLE_LOGGER="${ENABLE_LOGGER:-OFF}"
           -DENABLE_DEBUG=ON
           -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
           -DKDB_DB_SYSTEM="$SYSTEM_DIR"
